server:
  port: 8080
database:
  url: ${DB_URL}
jwt:
  accessToken:
    issuer: clubrizer.com
    headerName: Authorization
    secretKey: ${JWT_ACCESS_TOKEN_SECRET_KEY}
  refreshToken:
    issuer: clubrizer.com
    cookieName: clubrizer.refreshToken
    secretKey: ${JWT_REFRESH_TOKEN_SECRET_KEY}
    secure: ${JWT_REFRESH_TOKEN_SECURE}
    sameSite: Lax
  user:
    key: user
resend:
  apiKey: ${RESEND_API_KEY}
  fromAddress: noreply@clubrizer.com
gcs:
  profilePicturesBucketName: clubrizer_profile-pictures
otp:
  maxRequestsPerWindow: 5
  windowHours: 1
cors:
  allowedOrigins:
    - http://localhost:5173
    - https://lisc-2010.clubrizer.com
  allowedHeaders:
    - '*'